### ISSUE TITLE
Add support for `dispatch(...)` helper

### ISSUE THREAD

**Issue by JonasPardon** [JonasPardon/laravel-event-visualizer#11]

**Comment by JonasPardon** [comment]
Released in `v0.3.0`, but has to be verified that it works for all use cases.

**Comment by joelvh** [comment]
@JonasPardon there's also `dispatch_sync`

**Comment by JonasPardon** [comment]
> @JonasPardon there's also `dispatch_sync`

Will add support for that tonight if I find the time!

**Comment by JonasPardon** [comment]
@joelvh Support for `dispatch_sync` should work in [`v3.0.1`](https://github.com/JonasPardon/laravel-event-visualizer/releases/tag/v0.3.1)
