### ISSUE TITLE
Unable to install on L10+

### ISSUE THREAD

**Issue by RosiersRobin** [JonasPardon/laravel-event-visualizer#22]
Hi,

Unable to install on L10, since it's limited by `illuminate/contracts`.

**Comment by JonasPardon** [comment]
Hi @RosiersRobin ,

I tagged a new release with some version bumps, could you try installing again?

**Comment by JonasPardon** [comment]
Side note: it's using a pre-release dependency so you might have to set your minimum stability to dev. If it still doesn't work, posting the output here would be handy.

**Comment by JonasPardon** [comment]
Hi @RosiersRobin

It looks like your composer minimum stability is too high for a pre-release package (the mermaid-php one). 

I'll look into tagging an actual release for the `mermaid-php` package very soon, which should solve this issue.

If you want to install this right now, make sure to go to your `composer.json` and set `"minimum-stability": "dev"`, it should work while the package is pre-release.

**Comment by JonasPardon** [comment]
Figured I'd do it now real quick: I tagged a release for `v0.4.2` that has a stable version of the `mermaid-php` package, which should prevent you from needed to change your minimum stability.

Let me know if it works! 🤞🏻

**Comment by RosiersRobin** [comment]
Great! Works now! Thanksss!! I'll keep testing the package now :D
